/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KasirRouteImport } from './routes/kasir'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as PelangganRouteImport } from './routes/pelanggan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirRoute = KasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const PelangganRoute = PelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/katalog': typeof KatalogRoute
  '/laporan': typeof LaporanRoute
  '/pelanggan': typeof PelangganRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/katalog': typeof KatalogRoute
  '/laporan': typeof LaporanRoute
  '/pelanggan': typeof PelangganRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/katalog': typeof KatalogRoute
  '/laporan': typeof LaporanRoute
  '/pelanggan': typeof PelangganRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kasir' | '/katalog' | '/laporan' | '/pelanggan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kasir' | '/katalog' | '/laporan' | '/pelanggan'
  id: '__root__' | '/' | '/kasir' | '/katalog' | '/laporan' | '/pelanggan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KasirRoute: typeof KasirRoute
  KatalogRoute: typeof KatalogRoute
  LaporanRoute: typeof LaporanRoute
  PelangganRoute: typeof PelangganRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir': {
      id: '/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof KasirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelanggan': {
      id: '/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof PelangganRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KasirRoute: KasirRoute,
  KatalogRoute: KatalogRoute,
  LaporanRoute: LaporanRoute,
  PelangganRoute: PelangganRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
